name: Core

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * 1"

permissions:
  contents: write
  issues: write
  pull-requests: write
  checks: write
  actions: write
  deployments: write
  statuses: write
  packages: write
  pages: write
  repository-projects: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
      - name: Upgrade
        run: |
          apt update
          apt upgrade -y

      - name: Build zakosign
        run: |
          git clone https://github.com/Lama3L9R/zakosign.git --depth=1
          cd zakosign
          git submodule update --init --depth=1
          cd boringssl
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release .
          ninja -j$(nproc --all)
          sudo ninja install
          cd ..
          make -j$(nproc --all)

      - name: Upload
        if: success()
        uses: actions/upload-artifact@v4
        with:
            name: zakosign
            path: |
              zakosign/bin/*
        env:
            REPO: ${{ github.repository }}
        run: |
          cd zakosign/bin
          git init
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git branch -M build
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$REPO.git
          git add .
          git commit -a -m "Upload"
          git push -u origin build --force
